### ISSUE TITLE
memoize doesn’t have a facility similar to cached’s response_filter

### ISSUE THREAD

**Issue by gergelypolonkai** [sh4nks/flask-caching#107]
`cached` has a facility to ignore (ie. not cache) a return value based on the outcome of its `response_filter` parameter. `memoize` seems to lack such a functionality (see the discussion in #105). Right now it is easy to ignore `None` values (see #106) but it can’t be told to ignore other values.

**Comment by sh4nks** [comment]
I'd gladly review/accept a PR for this :-)

**Comment by gergelypolonkai** [comment]
On it already. I can hopefully send it tomorrow.

**Comment by filipebezerra** [comment]
I'm trying to figure out how `response_filter` behaves, it looks like it doens't prevent 500 responses. For instance let's suppose we setup redis backend and the application weren't able to connection because something bad happened to connect to redis instance, so it throws an `redis.exceptions.ConnectionError`, in the way the decorator `memoize` was written the `response_filter` calllable will not end up not having the chance to handle this connection error and the application will throw the 500 error to the client.

I'm write here folks?
