### ISSUE TITLE
AttributeError: 'Client' object has no attribute 'append'

### ISSUE THREAD

**Issue by patelnav** [sh4nks/flask-caching#120]
I'm using Flask-Caching on an Google AppEngine standard app as of v1.7.2. On python 2
I initialize Cache() without any params. (Defaults to memcached)

I see the following error on my local machine when using dev_appserver.py
Haven't tried to see what happens on live server.

```
Traceback (most recent call last):
  File "default/lib/flask_caching/__init__.py", line 785, in decorated_function
    found = self.cache.has(cache_key)
  File "default/lib/flask_caching/backends/memcache.py", line 148, in has
    return self._client.append(key, "")
AttributeError: 'Client' object has no attribute 'append'

```

**Comment by dmalis** [comment]
Live on GAE

Exception possibly due to cache backend.
Traceback (most recent call last):
File "/*****/lib/flask_caching/__init__.py", line 785, in decorated_function
found = self.cache.has(cache_key)
File "/****/lib/flask_caching/backends/memcache.py", line 148, in has
return self._client.append(key, "")
AttributeError: 'Client' object has no attribute 'append'

**Comment by sh4nks** [comment]
Mhh the memcache tests all passed. This seems to be a GAE problem right?

**Comment by gergelypolonkai** [comment]
Indeed, GAE doesn’t seem to support the `append` method; see documentation [here](https://cloud.google.com/appengine/docs/standard/python/refdocs/google.appengine.api.memcache).

**Comment by patelnav** [comment]
Hey @sh4nks any chance you can merge this change into the 1.7 branch for us python2 suckers.

**Comment by sh4nks** [comment]
@patelnav I'd merge a PR if you want to backport the fix.
