### ISSUE TITLE
Explicit fallback for cache.get()

### ISSUE THREAD

**Issue by fkromer** [sh4nks/flask-caching#137]
I am using an [explicitly caching data with flask_caching](https://flask-caching.readthedocs.io/en/latest/#explicitly-caching-data) with [a simple cache type](https://flask-caching.readthedocs.io/en/latest/#simplecache). In case the cache is not initialized and I call `cache.get()` it returns `None`. It would be great if one could define the fallback explicitly like possible and consistent with [`dict.get()`](https://docs.python.org/3.6/library/stdtypes.html?highlight=dict%20get#dict.get).

**Comment by huangxiaohen2738** [comment]
If the value returned by cache.get() is None, it
might be because the key is not found in the cache
or because the cached value is actually None

If you want to know it explicitly, you can set the `""` to replace the `None`
And you check the value `cache.get(key) is None`.

If true, the key was not exists, otherwise the value is `""`.

**Comment by gergelypolonkai** [comment]
That’s exactly the problem here: what if the value stored is actually `""`? And coming up with similar ideas to use funny defaults like `"aVeryUnlikelyValue"` has the same problem. What if the value is actually that?

**Comment by sh4nks** [comment]
While I like the idea, I am not keen on implementing it directly in the library. If you really need this functionality you can subclass a caching backend and implement it yourself for your application.
