### ISSUE TITLE
`key_prefix` parameter disregarded when `query_string` is set to `True`

### ISSUE THREAD

**Issue by avishavit** [sh4nks/flask-caching#165]
Hi, I see in the code for the `cached` method that if `query_string` is `True` then the method that is called is `make_cache_key_query_string` that's in https://github.com/sh4nks/flask-caching/blob/b8e2fa6d3251dc60548751855d1d329eecef132a/flask_caching/__init__.py#L464
then params are hashed, request path is added and the cache key does not reflect the `key_prefix` parameter.
Apart from other issues like post body not included, this makes the library a bit of an effort to integrate.

Would appreciate help, thanks!

**Comment by sh4nks** [comment]
When #159 is merged, you can provide your own make_cache_key functionality which I guess will solve this.

**Comment by amitt001** [comment]
@sh4nks Any technical reason for not adding prefix when `query_string=True`? I ran into this and this seemed like a bug to me.

**Comment by AndreLobato** [comment]
I've also ran into this. I don't see any reason why the `_make_cache_key_query_string` couldn't just be appended to the normal `_make_cache_key` function instead of doing this hard "if" clause.  

https://github.com/sh4nks/flask-caching/blob/f1899bc4522e090d94f68092364002df92aff49a/flask_caching/__init__.py#L532-L536

the `_make_cache_key_query_string` is still useful as performs the args hashing, so I am happy to use, but I also need to add a custom key_prefix. Having both options not working together in the same function without errors or warnings seems like a bug to me as well I am happy to submit a PR for that if that's agreed as the expected behaviour.
